---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/parameters/purpose.yaml
#include /includes/terms-of-service.yaml
#include /includes/lifetime-standard.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/num-users-salesforce.yaml
#include /includes/parameters/open-environment-annotation.yaml

# -------------------------------------------------------------------
# OpenShift Cluster to be used in the
# BASE RHODS environment on ROSA on RHPDS
# Catalog: OpenShift Workshops
# Catalog Item: BASED RHODS ON ROSA
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
platform: RHPDS

env_type: ocp4-cluster
software_to_deploy: openshift4

# -------------------------------------------------------------------
# End Mandatory Variables
# -------------------------------------------------------------------


# -------------------------------------------------------------------
# Repos
# -------------------------------------------------------------------

# Satellite is used for RHEL repos
repo_method: satellite

# Update RHEL to the latest packages (and reboot)
update_packages: true

# -------------------------------------------------------------------
# Generic Variables
# -------------------------------------------------------------------
cloudformation_retries: 0
install_ipa_client: false

# -------------------------------------------------------------------
# Student User on Bastion
# -------------------------------------------------------------------
install_student_user: true
# --- student_name not set -> Requestor User ID is used as student_name
student_name: lab-user
# --- student_password not set -> generate random password
# student_password: r3dh4t1!
# --- Student is allowed to sudo and switch to root
student_sudo: true

ocp_username: cluster-admin

# -------------------------------------------------------------------
# Infra Workloads
# -------------------------------------------------------------------
infra_workloads:
- ocp4_workload_generate_kubeconfig
- ocp4_workload_authentication_rosa
- ocp4_workload_opentlc_production
- ocp4_workload_project_request_template_rosa_aro
- ocp4_workload_pipelines
- ocp4_workload_rhods_self_managed
- ocp4_workload_web_terminal
- ocp4_workload_gitea_operator

# -------------------------------------------------------------------
# Student Workloads ([] means no student workloads)
# -------------------------------------------------------------------
student_workloads: []

# -------------------------------------------------------------------
# Authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_rosa_user_base: user
# When no password specified it is generated
ocp4_workload_authentication_rosa_user_password: Openshift@1
ocp4_workload_authentication_rosa_admin_password: Openshift@1

# -------------------------------------------------------------------
# OpenTLC Production
# -------------------------------------------------------------------
ocp4_workload_opentlc_production_remove_self_provisioner: false
ocp4_workload_opentlc_production_expose_registry_route: false
ocp4_workload_opentlc_production_set_build_defaults: true

# -------------------------------------------------------------------
# OpenShift Pipelines
# -------------------------------------------------------------------
ocp4_workload_pipelines_channel: pipelines-1.11
ocp4_workload_pipelines_csv_nameprefix: openshift-pipelines-operator-rh
ocp4_workload_pipelines_use_catalog_snapshot: false

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhods_self_managed
# -------------------------------------------------------------------
ocp4_workload_rhods_self_managed_operator_group_name: "rhods-ods-operator"
ocp4_workload_rhods_self_managed_operator_name: "rhods-operator"
ocp4_workload_rhods_self_managed_namespace: "redhat-ods-operator"
ocp4_workload_rhods_self_managed_channel: "stable"
ocp4_workload_rhods_self_managed_catalogsource_setup: false
ocp4_workload_rhods_self_managed_installPlanApproval: "Automatic"
ocp4_workload_rhods_self_managed_source: "redhat-operators"
ocp4_workload_rhods_self_managed_sourceNamespace: "openshift-marketplace"
ocp4_workload_rhods_self_managed_csv_nameprefix: "rhods-operator"
ocp4_workload_rhods_self_managed_startingCSV: "rhods-operator.1.28.1"
ocp4_workload_rhods_self_managed_namespace_list:
- "{{ ocp4_workload_rhods_self_managed_namespace }}"
ocp4_workload_rhods_self_managed_applications_namespace: "redhat-ods-applications"
ocp4_workload_rhods_self_managed_is_workshop: false
ocp4_workload_rhods_self_managed_workshop_num_users: 25
ocp4_workload_rhods_self_managed_workshop_username_base: "user"
ocp4_workload_rhods_self_managed_workshop_password: "{{ student_password }}"

# Variable for ocp4_workload_object_detection_ai_ml_setup
rhods_username: "admin"
ocp4_workload_aiml_namespace: "{{ rhods_username }}-rhods-project"
ocp4_workload_gitea_aiml_user: lab-user
retail_rhods_project_gitea_password: b3BlbnNoaWZ0
retail_rhods_project_gitea_username: bGFiLXVzZXI=

# ------------------------------------------------
# Web Terminal Operator
# ------------------------------------------------

ocp4_workload_web_terminal_operator_channel: "fast"
ocp4_workload_web_terminal_operator_automatic_install_plan_approval: true
ocp4_workload_web_terminal_operator_starting_csv: ""
ocp4_workload_web_terminal_operator_wait_for_deploy: true
ocp4_workload_web_terminal_operator_name: web-terminal
ocp4_workload_web_terminal_operator_csv_prefix: web-terminal
ocp4_workload_web_terminal_operator_catalog_source: redhat-operators
ocp4_workload_web_terminal_operator_deployment: web-terminal-controller
ocp4_workload_web_terminal_operator_namespace: openshift-operators
ocp4_workload_web_terminal_operator_use_catalog_snapshot: false
ocp4_workload_web_terminal_operator_catalogsource_name: redhat-operators-snapshot-amq-streams
ocp4_workload_web_terminal_operator_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_web_terminal_operator_catalog_snapshot_image_tag: "v4.13_2023_07_17"

# -------------------------------------------------------------------
# Workload: ocp4_workload_gitea_operator
# -------------------------------------------------------------------
ocp4_workload_gitea_operator_project: gitea

ocp4_workload_gitea_operator_catalog_image: quay.io/rhpds/gitea-catalog
ocp4_workload_gitea_operator_catalog_image_tag: v2.0.1
ocp4_workload_gitea_operator_gitea_image: quay.io/rhpds/gitea
ocp4_workload_gitea_operator_gitea_image_tag: 1.20.0

ocp4_workload_gitea_operator_deploy_gitea_instance: true
ocp4_workload_gitea_operator_name: gitea
ocp4_workload_gitea_operator_gitea_hostname: gitea
ocp4_workload_gitea_operator_gitea_volume_size: 2Gi
ocp4_workload_gitea_operator_postgresql_volume_size: 2Gi
ocp4_workload_gitea_operator_ssl_route: true

ocp4_workload_gitea_operator_disable_registration: false
ocp4_workload_gitea_operator_enable_captcha: false
ocp4_workload_gitea_operator_allow_create_organization: true
ocp4_workload_gitea_operator_register_email_confirm: false
ocp4_workload_gitea_operator_enable_notify_email: false
ocp4_workload_gitea_operator_mailer_enabled: false

ocp4_workload_gitea_operator_create_admin: true
ocp4_workload_gitea_operator_admin_user: opentlc-mgr
ocp4_workload_gitea_operator_admin_email: opentlc-mgr@opentlc.com
ocp4_workload_gitea_operator_admin_password: openshift

ocp4_workload_gitea_operator_create_users: true
ocp4_workload_gitea_operator_user_number: 1
ocp4_workload_gitea_operator_generate_user_format: lab-user
ocp4_workload_gitea_operator_user_password: openshift
ocp4_workload_gitea_operator_migrate_repositories: true
ocp4_workload_gitea_operator_repositories_list:
- repo: https://github.com/Enterprise-Neurosystem/edge-anomaly-detection.git
  name: edge-anomaly-detection
  private: false
- repo: https://github.com/Enterprise-Neurosystem/edge-prediction-failure.git
  name: edge-prediction-failure
  private: false
- repo: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
  name: edge-cluster-bootstrap
  private: false
- repo: https://github.com/Enterprise-Neurosystem/edge-synthetic-data-generator.git
  name: edge-synthetic-data-generator
  private: false
