---
ocp_username: kubeadmin

infra_workloads:
- ocp4-workload-workshop-admin-storage
- ocp4_workload_pipelines
- ocp4_workload_rhacs
- ocp4_workload_rhacm

# -------------------------------------------------------------------
# Common Password
# -------------------------------------------------------------------
common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhacm
# -------------------------------------------------------------------

ocp4_workload_rhacm_acm_channel: "release-2.6"
ocp4_workload_rhacm_use_catalog_snapshot: true
ocp4_workload_rhacm_catalogsource_name: catalogsource-rhacm
ocp4_workload_rhacm_catalog_source_image: "quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog"
ocp4_workload_rhacm_catalog_source_tag: "v4.12_2023_02_20"

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhacs
# -------------------------------------------------------------------
ocp4_workload_rhacs_install_operator_channel: "rhacs-3.73"
ocp4_workload_rhacs_install_operator_starting_csv: "rhacs-operator.v3.73.1"
ocp4_workload_rhacs_install_operator_use_catalog_snapshot: true
#ocp4_workload_rhacs_install_operator_catalog_source_tag: "v4.10_2022_04_04"
ocp4_workload_rhacs_central_admin_password: "{{ common_password }}"

# -------------------------------------------------------------------
# Workload: ocp4_workload_pipelines
# -------------------------------------------------------------------
ocp4_workload_pipelines_channel: pipelines-1.8
ocp4_workload_pipelines_csv_nameprefix: openshift-pipelines-operator-rh
ocp4_workload_pipelines_use_catalog_snapshot: false

# -------------------------------------------------------------------
# Other Variables
# -------------------------------------------------------------------
WORKSHOP_FILE: workshop-appmod.yaml
HOMEROOM_IMAGE: ocp4-prod
