---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/parameters/purpose.yaml
#include /includes/terms-of-service.yaml
#include /includes/lifetime-standard.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/ocp4-fips-enable.yaml
#include /includes/parameters/agnosticd_open_environment.yaml

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------
platform: RHPDS

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ocp4-cluster
software_to_deploy: openshift4
ocp4_installer_version: "4.12.12"
ocp4_installer_root_url: http://mirror.openshift.com/pub/openshift-v4/clients
master_instance_count: 1
worker_instance_count: 0
bastion_instance_image: RHEL87GOLD-latest

# -------------------------------------------------------------------
# Repos
# -------------------------------------------------------------------
repo_method: satellite
update_packages: true

common_packages_el8:
- make
- unzip
- golang

# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
# --- Infra Workloads (YAML List)
infra_workloads:
- bookbag
- ocp4_workload_le_certificates

# --- Student Workloads (YAML List)
student_workloads: []

host_ocp4_installer_set_user_data_kubeadmin_password: true

# -------------------------------------------------------------------
# Bookbag variables
# -------------------------------------------------------------------
bookbag_git_repo: https://github.com/piparul/kepler-labdemo-bookbag.git
bookbag_git_version: main

# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------
__meta__:
  aws_sandboxed: true
  anarchy:
    namespace: babylon-anarchy-sandboxes-gpte
  catalog:
    icon:
      alt: Sustainable Computing - Kepler
      url: https://gpte-public.s3.amazonaws.com/babylon-catalog/OCP_Kepler_Sustainable.gif
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: Sustainable Computing
    category: Demos
    multiuser: false
    keywords:
    - openshift
    - ocp
    labels:
      Product: Red_Hat_OpenShift_Container_Platform
      Provider: RHDP
      Product_Family: Red_Hat_Cloud
    parameters:
    - name: ocp4_installer_version
      description: Version of OpenShift to Install
      formLabel: OpenShift Version
      required: true
      openAPIV3Schema:
        type: string
        default: '4.12.12'
        enum:
        - '4.8'
        - '4.9'
        - '4.10'
        - '4.11.36'
        - '4.12.12'

    - name: master_instance_type
      description: OpenShift compute master instance type
      formLabel: Control Plane Instance Type
      openAPIV3Schema:
        type: string
        default: m5.xlarge
        enum:
        - m5.xlarge
        - m5.2xlarge
        - m5.4xlarge

  deployer:
    virtualenv: ansible2.9-python3.6-2022-07-27
