---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/terms-of-service.yaml
#include /includes/lifetime-standard.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/parameters/purpose.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/ocp4-fips-enable.yaml
#include /includes/parameters/num-users-salesforce.yaml
#include /includes/parameters/agnosticd_open_environment.yaml
#include /includes/secrets/cockroach_dbaas_amq_lab_apikey.yaml

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ocp4-cluster
software_to_deploy: openshift4

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------
platform: RHPDS

# -------------------------------------------------------------------
# OpenShift Version
# -------------------------------------------------------------------
ocp4_installer_version: "4.12.12"
ocp4_installer_root_url: http://mirror.openshift.com/pub/openshift-v4/clients
ocp4_installer_use_dev_preview: false
# ocp4_installer_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/fast-4.12/openshift-install-linux.tar.gz
# ocp4_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/fast-4.12/openshift-client-linux.tar.gz


# -------------------------------------------------------------------
# Student User on Bastion
# -------------------------------------------------------------------
install_student_user: true
student_name: lab-user
student_sudo: true


# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
# --- Infra Workloads (YAML List)
infra_workloads:
- ocp4_workload_authentication
- ocp4_workload_opentlc_production
#- ocp4_workload_le_certificates
- ocp4_workload_gitea_operator
- ocp4_workload_dbaas_operator
- ocp4_workload_amq_streams
- ocp4_workload_gitea_operator
- ocp4_workload_pipelines
- ocp4_workload_cockroach_dbaas_amq_lab
- bookbag

# --- Student Workloads (YAML List)
student_workloads: []

# -------------------------------------------------------------------
# Workload: ocp4_workload_authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_admin_user: admin
# Generate admin password
ocp4_workload_authentication_htpasswd_admin_password: ""
ocp4_workload_authentication_htpasswd_admin_password_length: 16
ocp4_workload_authentication_htpasswd_user_base: user
# Generate user password
ocp4_workload_authentication_htpasswd_user_password: ""
ocp4_workload_authentication_htpasswd_user_password_length: 16
ocp4_workload_authentication_htpasswd_user_count: "{{ user_count | default(num_users) | default('2') | int }}"
ocp4_workload_authentication_remove_kubeadmin: true

# -------------------------------------------------------------------
# Workload: ocp4_workload_opentlc_production
# -------------------------------------------------------------------
ocp4_workload_opentlc_production_remove_self_provisioner: false

### gitea
ocp4_workload_gitea_operator_create_admin: true
ocp4_workload_gitea_operator_admin_password: openshift
ocp4_workload_gitea_operator_create_users: true
ocp4_workload_gitea_operator_user_password: openshift
ocp4_workload_gitea_operator_migrate_repositories: true
ocp4_workload_gitea_operator_repositories_list:
- repo: "https://github.com/shettyjm/rhedalab.git"
  name: "cockroach-kafka-eda"
  private: false

### bookbag
bookbag_git_repo: https://github.com/OpenShiftDemos/cockroachdb-kafka-eda-lab

# -------------------------------------------------------------------
# AgnosticV meta variables
# -------------------------------------------------------------------
agnosticv_meta:
  deploy_with: babylon
  params_to_variables:
    username: student_name

# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------
__meta__:
  anarchy:
    namespace: babylon-anarchy-ocp-wksp
  aws_sandboxed: true
  deployer:
    virtualenv: ansible2.9-python3.6-2021-11-30
  catalog:
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: Architecting event-driven apps with OpenShift CockroachDB Kafka
    category: Workshops
    keywords:
    - workshop
    - openshift
    - kafka
    - eda
    - cockroach
    - summit 2023
    labels:
      Product: Red_Hat_OpenShift_Container_Platform
      Product_Family: Red_Hat_Cloud
      Provider: RHDP
    multiuser: true
    parameters:
    - name: num_users
      description: >-
        Number of users to provision within the cluster.
      formLabel: OpenShift User Count
      openAPIV3Schema:
        type: integer
        default: 2
        minimum: 2
  secrets:
  - namespace: gpte
    name: ocp4-token
  - namespace: gpte
    name: satellite-rhel8-latest-ha
  - name: output-dir-s3
    namespace: gpte
