---
ocp_username: cluster-admin

infra_workloads:
- ocp4-workload-workshop-admin-storage
- studentvm_ocp4
- ocp4_workload_pipelines
- ocp4_workload_rhacs
- ocp4_workload_rhacm
- ocp4_workload_le_certificates

# -------------------------------------------------------------------
# Workload: ocp4_workload_authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_managed_ocp_htpasswd_user_base: user
# When no password specified it is generated
ocp4_workload_authentication_managed_ocp_htpasswd_user_password: openshift
ocp4_workload_authentication_htpasswd_user_password: "{{ ocp4_workload_authentication_managed_ocp_htpasswd_user_password }}"

# -------------------------------------------------------------------
# Common Password
# -------------------------------------------------------------------
common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhacm
# -------------------------------------------------------------------

ocp4_workload_rhacm_use_catalog_snapshot: true
ocp4_workload_rhacm_catalog_source_image: "quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog"
ocp4_workload_rhacm_catalog_source_tag: "v4.10_2022_08_01"
ocp4_workload_rhacm_acm_csv: "advanced-cluster-management.v2.5.1"
ocp4_workload_rhacm_acm_channel: "release-2.5"
ocp4_workload_rhacm_acm_release: "release-2.5"

ocp4_workload_rhacs_central_admin_password: "{{ common_password }}"

# -------------------------------------------------------------------
# Workload: ocp4_workload_pipelines
# -------------------------------------------------------------------
ocp4_workload_pipelines_channel: stable
ocp4_workload_pipelines_use_catalog_snapshot: true
ocp4_workload_pipelines_catalog_snapshot_image_tag: v4.9_2022_02_07
ocp4_workload_pipelines_catalogsource_name: redhat-operators-snapshot-pipelines
ocp4_workload_pipelines_csv_nameprefix: openshift-pipelines-operator-rh

# -------------------------------------------------------------------
# Student User on Bastion
# -------------------------------------------------------------------
# --- Student User on Bastion
install_student_user: true
# --- student_name not set -> Requestor User ID is used as student_name
student_name: demo-user
# --- student_password not set -> generate random password
# student_password: r3dh4t1!
# --- Student is allowed to sudo and switch to root
student_sudo: true

# --- Student Workloads (YAML List)
student_workloads: []

# Enable if the item is being deployed to a sandbox account
# and you want credentials provided to the user
sandbox_student_user: true

# -------------------------------------------------------------------
# Other Variables
# -------------------------------------------------------------------
install_ftl: false
WORKSHOP_FILE: workshop-appmod.yaml
