---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/parameters/purpose.yaml
#include /includes/terms-of-service.yaml
#include /includes/lifetime-standard.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/num-users-salesforce.yaml
#include /includes/parameters/open-environment-annotation.yaml

# -------------------------------------------------------------------
# OpenShift Cluster to be used in the
# OCP 4 Starter Workshop on RHPDS
# Catalog: OpenShift Workshops
# Catalog Item: OpenShift 4 Starter Workshop - TRAINING, SMALL, LARGE
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
platform: RHPDS

env_type: ocp4-cluster
software_to_deploy: openshift4
# -------------------------------------------------------------------
# End Mandatory Variables
# -------------------------------------------------------------------


# -------------------------------------------------------------------
# Repos
# -------------------------------------------------------------------

# Satellite is used for RHEL repos
repo_method: satellite

# Update RHEL to the latest packages (and reboot)
update_packages: true

# -------------------------------------------------------------------
# Generic Variables
# -------------------------------------------------------------------
cloudformation_retries: 0
install_ipa_client: false

# -------------------------------------------------------------------
# Student User on Bastion
# -------------------------------------------------------------------
install_student_user: true
# --- student_name not set -> Requestor User ID is used as student_name
student_name: lab-user
# --- student_password not set -> generate random password
# student_password: r3dh4t1!
# --- Student is allowed to sudo and switch to root
student_sudo: true

# -------------------------------------------------------------------
# Infra Workloads
# -------------------------------------------------------------------
infra_workloads:
- ocp4_workload_generate_kubeconfig
- ocp4_workload_authentication
- ocp4_workload_opentlc_production
- ocp4_workload_project_request_template_rosa_aro
- ocp4_workload_pipelines
- ocp4_workload_rhods_self_managed

# -------------------------------------------------------------------
# Student Workloads ([] means no student workloads)
# -------------------------------------------------------------------
student_workloads: []

# -------------------------------------------------------------------
# Authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_admin_user: opentlc-mgr
# When no password specified it is generated
ocp4_workload_authentication_htpasswd_admin_password: r3dh4t1!
ocp4_workload_authentication_htpasswd_user_base: user
# When no password specified it is generated
ocp4_workload_authentication_htpasswd_user_password: openshift

# Create 'user_count' student users
ocp4_workload_authentication_htpasswd_user_count: "{{ (num_users | default('2')) | int }}"

# Remove the standard kubeadmin user
ocp4_workload_authentication_remove_kubeadmin: false

# -------------------------------------------------------------------
# OpenTLC Production
# -------------------------------------------------------------------
ocp4_workload_opentlc_production_remove_self_provisioner: false
ocp4_workload_opentlc_production_expose_registry_route: false
ocp4_workload_opentlc_production_set_build_defaults: true

# Details of the Limit Range.
ocp4_workload_project_request_template_limits:
- type: Container
  max:
    cpu: 16
    memory: 32Gi
  default:
    cpu: 500m
    memory: 1.5Gi
  defaultRequest:
    cpu: 50m
    memory: 256Mi
- type: Pod
  max:
    cpu: 16
    memory: 32Gi

# -------------------------------------------------------------------
# OpenShift Pipelines
# -------------------------------------------------------------------
ocp4_workload_pipelines_channel: pipelines-1.11
ocp4_workload_pipelines_csv_nameprefix: openshift-pipelines-operator-rh
ocp4_workload_pipelines_use_catalog_snapshot: false

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhods_self_managed
# -------------------------------------------------------------------
ocp4_workload_rhods_self_managed_operator_group_name: "rhods-ods-operator"
ocp4_workload_rhods_self_managed_operator_name: "rhods-operator"
ocp4_workload_rhods_self_managed_namespace: "redhat-ods-operator"
ocp4_workload_rhods_self_managed_channel: "stable"
ocp4_workload_rhods_self_managed_catalogsource_setup: false
ocp4_workload_rhods_self_managed_installPlanApproval: "Automatic"
ocp4_workload_rhods_self_managed_source: "redhat-operators"
ocp4_workload_rhods_self_managed_sourceNamespace: "openshift-marketplace"
ocp4_workload_rhods_self_managed_csv_nameprefix: "rhods-operator"
ocp4_workload_rhods_self_managed_startingCSV: "rhods-operator.1.28.1"
ocp4_workload_rhods_self_managed_namespace_list:
- "{{ ocp4_workload_rhods_self_managed_namespace }}"
ocp4_workload_rhods_self_managed_applications_namespace: "redhat-ods-applications"
ocp4_workload_rhods_self_managed_is_workshop: false
ocp4_workload_rhods_self_managed_workshop_num_users: 25
ocp4_workload_rhods_self_managed_workshop_username_base: "user"
ocp4_workload_rhods_self_managed_workshop_password: "{{ student_password }}"

# Variable for ocp4_workload_object_detection_ai_ml_setup
rhods_username: "admin"
ocp4_workload_aiml_namespace: "{{ rhods_username }}-rhods-project"
ocp4_workload_gitea_aiml_user: lab-user
retail_rhods_project_gitea_password: b3BlbnNoaWZ0
retail_rhods_project_gitea_username: bGFiLXVzZXI=
