---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/parameters/purpose.yaml
#include /includes/terms-of-service.yaml
#include /includes/lifetime-standard.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/ocp4-fips-enable.yaml
#include /includes/parameters/agnosticd_open_environment.yaml
#include /includes/access-restriction-summit2023-devs.yaml
#include /includes/secrets/bookbag-shared-410.yaml

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------

platform: RHPDS

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ocp4-cluster
software_to_deploy: openshift4
ocp4_installer_version: "4.12.12"
ocp4_installer_root_url: http://mirror.openshift.com/pub/openshift-v4/clients
master_instance_count: 1
worker_instance_count: 0
bastion_instance_image: RHEL86GOLD-latest

common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"

# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
# --- Infra Workloads (YAML List)

requirements_content:
  collections:
    - name: kubernetes.core
      version: 2.3.1
    - name: openstack.cloud
      version: 1.7.2
    - name: amazon.aws
      version: 2.2.0
    - name: community.general
      version: 4.6.1
    - name: ansible.posix
      version: 1.3.0
    - name: awx.awx
      version: 21.4.0
    - name: ansible.utils
      version: 2.7.0

infra_workloads:

  - ocp4_workload_le_certificates
  - ocp4_workload_ansible_automation_platform
  - bookbag

# workload ocp4_workload_ansible_automation_platform vars

ocp4_workload_ansible_automation_platform_admin_password: "{{ common_password }}"
ocp4_workload_ansible_automation_platform_manifest:
  url: https://d3s3zqyaz8cp2d.cloudfront.net/aap/manifest.zip
  inject: true

# workload bookbag vars

bookbag_git_repo: https://github.com/rlopez133/bookbag

# --- Student Workloads (YAML List)
student_workloads: []

host_ocp4_installer_set_user_data_kubeadmin_password: true

# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------
__meta__:
  aws_sandboxed: true
  anarchy:
    namespace: babylon-anarchy-sandboxes-gpte
  catalog:
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: Ansible Automation Platform 2 EDA on OpenShift
    category: Demos
    multiuser: false
    keywords:
      - eda
      - ansible
      - openshift
      - ocp
      - summit
    labels:
      Product: Red_Hat_OpenShift_Container_Platform
      Provider: RHDP
      Product_Family: Red_Hat_Cloud
    parameters:

      - name: master_instance_type
        description: OpenShift compute master instance type
        formLabel: Control Plane Instance Type
        openAPIV3Schema:
          type: string
          default: c6a.2xlarge
          enum:
            - c6a.2xlarge
            - m6a.xlarge
            - m6a.2xlarge
            - m6a.4xlarge

  deployer:
    virtualenv: ansible2.9-python3.6-2022-07-27